### ISSUE TITLE
Fix responsive layout for page body on small devices

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/officeuifabric.github.io#37]
Looks fine on large screens but tablets and phones screw up with poor use of CSS by yours truly.

**Comment by StfBauer** [comment]
I would prefer to upgrade this to SUSY. Better control, smaller code and works way better.

**Comment by StfBauer** [comment]
OK found it. Grid ist currently not defined in patterns.

**Comment by andrewconnell** [comment]
Not familiar with SUSY... looking at the site for SUSY, I'm not sure how it addresses this issue.

**Comment by StfBauer** [comment]
Found the Issue. It was not released with Version 1.0.   
```
<link rel="stylesheet" href="//appsforoffice.microsoft.com/fabric/1.0/fabric.min.css" />
 <link rel="stylesheet" href="//appsforoffice.microsoft.com/fabric/1.0/fabric.components.min.css" />
```
Those have no media queries included or at least not the one we need to use.
The current repository includes them but not the links above.

**Comment by andrewconnell** [comment]
Ah... so the CDN 1.0.0 versions don't include media queries but the repo on GitHub does have it? That makes sense... thanks! I'll factor that when I revisit it.

**Comment by StfBauer** [comment]
Yes exactly.
