### ISSUE TITLE
Live Demo of UI Elements on the web site

### ISSUE THREAD

**Issue by StfBauer** [ngOfficeUIFabric/officeuifabric.github.io#38]
It would be nice if the web site would show a live demo of all available components.

**Comment by andrewconnell** [comment]
This is in process... i'm working on it... look at all the other issues here as I'm plugging through each one. Please see the "what's next" part of this post for some details: http://www.andrewconnell.com/blog/introducing-officeuifabric-com-demos-and-reference-samples-for-office-ui-fabric
