### ISSUE TITLE
Update the documentation to version 1.1.2

### ISSUE THREAD

**Issue by EphraimB** [ngOfficeUIFabric/officeuifabric.github.io#50]

**Comment by andrewconnell** [comment]
Thanks for submitting, but this isn't something I'm going to do. Please see this for more info: http://www.andrewconnell.com/blog/officeuifabric-com-v1-0-0-full-sample-coverage-of-office-ui-fabric-v1-0-0

Of course if you'd like to submit a PR with updates I'd be happy to merge it in.
