### ISSUE TITLE
Search box component of Office UI fabric is not displayed correctly in IE 11

### ISSUE THREAD

**Issue by aleks-zhigar** [ngOfficeUIFabric/officeuifabric.github.io#51]
![ie11-search-box](https://cloud.githubusercontent.com/assets/8442105/10336607/9bb88b1a-6d02-11e5-9b3e-20625d8c66ab.png)
The box is displayed correctly in Chrome and Firefox.

**Comment by andrewconnell** [comment]
Thanks... but this isn't likely to get fixed unless you want to submit a fix as a PR since the site is temporary. More info here.

http://www.andrewconnell.com/blog/officeuifabric-com-v1-0-0-full-sample-coverage-of-office-ui-fabric-v1-0-0
