### ISSUE TITLE
Buttons as <a> and as <div> can not be clicked on the caption in IE11

### ISSUE THREAD

**Issue by aleks-zhigar** [ngOfficeUIFabric/officeuifabric.github.io#52]

**Comment by andrewconnell** [comment]
This isn't the official Office UI Fabric... this is a community project. Please submit issues against the MSFT owned resource. More info here:

http://www.andrewconnell.com/blog/officeuifabric-com-v1-0-0-full-sample-coverage-of-office-ui-fabric-v1-0-0
