### ISSUE TITLE
Issues with the table component of Office UI Fabric

### ISSUE THREAD

**Issue by aleks-zhigar** [ngOfficeUIFabric/officeuifabric.github.io#53]
When scrolling down lines in a table, table header is not fixed, but moves out of sight with other table lines. 
There is no possibility to create a table without a header.

**Comment by andrewconnell** [comment]
This is not the official Office UI Fabric channel... this is a community project. Please see this for more information.

http://www.andrewconnell.com/blog/officeuifabric-com-v1-0-0-full-sample-coverage-of-office-ui-fabric-v1-0-0
