### ISSUE TITLE
Icon display page is not returning icons

### ISSUE THREAD

**Issue by VeldMuijz** [ngOfficeUIFabric/officeuifabric.github.io#54]
Hi there,
Really love your examples page, it helped me a lot. 
Today I tried to view your Icons page and it failed. The browser cannot get the files:
![image](https://cloud.githubusercontent.com/assets/1394439/10539516/4bb36acc-7400-11e5-97f7-c1e05969e3cf.png)

Thought I'd let you know.

**Comment by andrewconnell** [comment]
Looks good from my side... can't repo... can't see the errors in the tiny screenshot or browser you're running this in. At any rate, not something I'd likely fix as this site is going away soon.
